apiVersion: v1
kind: Service
metadata:
  name: cache-client-service
spec:
  type: NodePort
  ports:
    - port: 2001
      nodePort: 32001
      targetPort: 2001
      protocol: TCP
  selector:
    name: cache-client